### ISSUE TITLE
500 Errors on Evaluations route

### ISSUE THREAD

**Issue by JimmyAstle** [mitre-attack/joystick#1]
When trying to naviagte to the evaluations portion of this app I get the following error:
`
INFO:aiohttp.access:127.0.0.1 [08/Apr/2020:15:36:05 +0000] "GET /evaluations HTTP/1.1" 500 334 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp_jinja2/__init__.py", line 122, in wrapped
    context = await coro(*args)
  File "/opt/joystick/app/api/rest_api.py", line 89, in evaluations
    evaluations = await self.data_svc.get_evaluations()
  File "/opt/joystick/app/service/data_svc.py", line 105, in get_evaluations
    evals = await self.get_tables()
  File "/opt/joystick/app/service/data_svc.py", line 54, in get_tables
    tables = [table for table in self.db.tables()]
AttributeError: 'NoneType' object has no attribute 'tables'
`

Is there a way to verify my local database exists / is healthy?

**Comment by JimmyAstle** [comment]
With the recent update things are now working
