### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 20837: character maps to <undefined>

### ISSUE THREAD

**Issue by Barakkl** [mitre-attack/joystick#4]
Missing encoding in file open, need to line 13 in update file_svc.py :
From: with open(file) as json_file:
To: with open(file, **encoding="utf8")** as json_file:

This is the error I'm getting:
Traceback (most recent call last):
  File "joystick.py", line 55, in <module>
    main(config_host, config_port, services)
  File "joystick.py", line 36, in main
    loop.run_until_complete(data_svc.load_evaluations())
  File "C:\Users\******\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\******\Downloads\MITRE_JOYSTICK\joystick\app\service\data_svc.py", line 32, in load_evaluations
    results = await self.get_service('file_svc').load_json_file(evaluation)
  File "C:\Users\******\Downloads\MITRE_JOYSTICK\joystick\app\service\file_svc.py", line 14, in load_json_file
    data = json.load(json_file)
  File "C:\Users\******\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\******\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 20837: character maps to <undefined>

**Comment by itpropaul** [comment]
I'm getting this same error with latest Python 3.8.2 and latest PIP pip-20.1 on Win10

**Comment by heyibrahimkhan** [comment]
Getting the same error with Python 3.8.3 on Windows 10.
![image](https://user-images.githubusercontent.com/14034237/93631888-cda2cb00-fa05-11ea-803c-33195b63f6ac.png)

**Comment by sujantkumarkv** [comment]
Yes the same error on Python 3.9 Win10 .

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
